/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sap.successfactors.Gerente;
import sap.successfactors.Pantalla_Inicio;
import sap.successfactors.Gerente.Crear_Formulario;

/**
 *
 * @author PC
 */
public class Pantalla_JefeRRHH extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Gerente
     */
    public Pantalla_JefeRRHH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_CrearFormulario = new javax.swing.JButton();
        Btn_VerFormularios = new javax.swing.JButton();
        Btn_BorrarFormularios = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        Btn_SeleccionarCandidatos = new javax.swing.JButton();
        Btn_Entrevistar = new javax.swing.JButton();
        Btn_BorrarEntrevista = new javax.swing.JButton();
        Btn_VerEntrevista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_CrearFormulario.setText("Crear formulario");
        btn_CrearFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearFormularioActionPerformed(evt);
            }
        });

        Btn_VerFormularios.setText("Ver formularios");
        Btn_VerFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerFormulariosActionPerformed(evt);
            }
        });

        Btn_BorrarFormularios.setText("Borrar formularios");
        Btn_BorrarFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BorrarFormulariosActionPerformed(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        Btn_SeleccionarCandidatos.setText("Seleccionar Candidatos");
        Btn_SeleccionarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SeleccionarCandidatosActionPerformed(evt);
            }
        });

        Btn_Entrevistar.setText("Entrevistar Candidatos");
        Btn_Entrevistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EntrevistarActionPerformed(evt);
            }
        });

        Btn_BorrarEntrevista.setText("Borrar Entrevista");
        Btn_BorrarEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BorrarEntrevistaActionPerformed(evt);
            }
        });

        Btn_VerEntrevista.setText("Ver Entrevistas");
        Btn_VerEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerEntrevistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_volver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_VerEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_SeleccionarCandidatos)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Btn_BorrarFormularios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_VerFormularios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_CrearFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Entrevistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_BorrarEntrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_volver)
                .addGap(14, 14, 14)
                .addComponent(btn_CrearFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_VerFormularios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BorrarFormularios)
                .addGap(4, 4, 4)
                .addComponent(Btn_Entrevistar)
                .addGap(11, 11, 11)
                .addComponent(Btn_VerEntrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_BorrarEntrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_SeleccionarCandidatos)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VerFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerFormulariosActionPerformed
        Ver_Formulario ver=new Ver_Formulario();
        ver.setLocationRelativeTo(null);
        ver.setVisible(true);
    }//GEN-LAST:event_Btn_VerFormulariosActionPerformed

    private void btn_CrearFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearFormularioActionPerformed
        Crear_Formulario vM = new Crear_Formulario();
        this.setVisible(false);
        vM.setLocationRelativeTo(null);
        vM.setVisible(true);
    }//GEN-LAST:event_btn_CrearFormularioActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Pantalla_Inicio vM = new Pantalla_Inicio();
        this.setVisible(false);
        vM.setSize(600,500);
        vM.setLocationRelativeTo(null);
        vM.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void Btn_BorrarFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BorrarFormulariosActionPerformed
        Borrar_Formulario vB = new Borrar_Formulario();
        this.setVisible(false);
        vB.setLocationRelativeTo(null);
        vB.setVisible(true);
    }//GEN-LAST:event_Btn_BorrarFormulariosActionPerformed

    private void Btn_SeleccionarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SeleccionarCandidatosActionPerformed
        Seleccionar_Candidato vS = new Seleccionar_Candidato();
        this.setVisible(false);
        vS.setLocationRelativeTo(null);
        vS.setVisible(true);
    }//GEN-LAST:event_Btn_SeleccionarCandidatosActionPerformed

    private void Btn_EntrevistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EntrevistarActionPerformed
        Crear_Entrevista vS = new Crear_Entrevista();
        this.setVisible(false);
        vS.setLocationRelativeTo(null);
        vS.setVisible(true);
    }//GEN-LAST:event_Btn_EntrevistarActionPerformed

    private void Btn_BorrarEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BorrarEntrevistaActionPerformed
        Borrar_Entrevista vS = new Borrar_Entrevista();
        this.setVisible(false);
        vS.setLocationRelativeTo(null);
        vS.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_BorrarEntrevistaActionPerformed

    private void Btn_VerEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerEntrevistaActionPerformed
        Ver_Entrevista vS = new Ver_Entrevista();
        this.setVisible(false);
        vS.setLocationRelativeTo(null);
        vS.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_VerEntrevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_JefeRRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_JefeRRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_JefeRRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_JefeRRHH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_JefeRRHH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BorrarEntrevista;
    private javax.swing.JButton Btn_BorrarFormularios;
    private javax.swing.JButton Btn_Entrevistar;
    private javax.swing.JButton Btn_SeleccionarCandidatos;
    private javax.swing.JButton Btn_VerEntrevista;
    private javax.swing.JButton Btn_VerFormularios;
    private javax.swing.JButton btn_CrearFormulario;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
