/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sap.successfactors.Candidato;

import javax.swing.JFileChooser;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import sap.successfactors.ConexionBDD;

/**
 *
 * @author PC
 */
public class Registrarse extends javax.swing.JFrame {
    private File archivoSeleccionado;
    private JTextField txtRutaArchivo;
    ConexionBDD conexion=new ConexionBDD();
    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        txtRutaArchivo = new JTextField();
        txtRutaArchivo.setBounds(120, 20, 250, 25);
        txtRutaArchivo.setEditable(false);
        add(txtRutaArchivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtf_Nombre = new javax.swing.JTextField();
        txtf_Apellido = new javax.swing.JTextField();
        txtf_Contraseña = new javax.swing.JTextField();
        btn_Seleccionar = new javax.swing.JButton();
        btn_Subir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtf_Nombre.setText("jTextField1");

        txtf_Apellido.setText("jTextField1");

        txtf_Contraseña.setText("jTextField1");

        btn_Seleccionar.setText("Seleccionar archivo");
        btn_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarActionPerformed(evt);
            }
        });

        btn_Subir.setText("Subir");
        btn_Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Seleccionar)
                    .addComponent(txtf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Subir)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(txtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btn_Seleccionar)
                .addGap(18, 18, 18)
                .addComponent(btn_Subir)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarActionPerformed
/*
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoSeleccionado = fileChooser.getSelectedFile();
            if (archivoSeleccionado == null) {
    System.out.println("Error: archivoSeleccionado es null al intentar subir.");
} else {
    System.out.println("Archivo listo para subir: " + archivoSeleccionado.getAbsolutePath());
}

            // Verifica que no sea nulo y que el archivo tenga extensión PDF
            if (archivoSeleccionado != null && archivoSeleccionado.getName().endsWith(".pdf")) {
                if (archivoSeleccionado == null) {
    System.out.println("Error: archivoSeleccionado es null al intentar subir.");
} else {
    System.out.println("Archivo listo para subir: " + archivoSeleccionado.getAbsolutePath());
}
                if (txtRutaArchivo != null) {
    txtRutaArchivo.setText(archivoSeleccionado.getAbsolutePath());
} else {
    System.out.println("txtRutaArchivo es null. Asegúrate de inicializarlo correctamente.");
}

                txtRutaArchivo.setText(archivoSeleccionado.getAbsolutePath());
                if (archivoSeleccionado == null) {
    System.out.println("Error: archivoSeleccionado es null al intentar subir.");
} else {
    System.out.println("Archivo listo para subir: " + archivoSeleccionado.getAbsolutePath());
}
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un archivo PDF válido.");
                archivoSeleccionado = null; // Resetea en caso de archivo inválido
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó ningún archivo.");
            archivoSeleccionado = null; // Resetea en caso de cancelar
        }

          */  
    }//GEN-LAST:event_btn_SeleccionarActionPerformed

    private void btn_SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubirActionPerformed
        /*
        if (archivoSeleccionado != null) {
            conexion.subirArchivo(archivoSeleccionado);
        } else {
            JOptionPane.showMessageDialog(null, "No hay archivo seleccionado para subir.");
        }
    */
    }//GEN-LAST:event_btn_SubirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Seleccionar;
    private javax.swing.JButton btn_Subir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtf_Apellido;
    private javax.swing.JTextField txtf_Contraseña;
    private javax.swing.JTextField txtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
